class Buyer:
	"""Class that represents a Buyer"""

	class GenderEnum:
		Male = 'M'
		Female = 'F'

	class PersonTypeEnum:
		Person = 'Person'
		Company = 'Company'

	class DocumentType:
		CPF = 'CPF'
		CNPJ = 'CNPJ'		
	
	def __init__(self):		
		# Buyer custom identification [String]
		self.buyerReference = None

		# Email address [String]
		self.email = None

		# Facebook ID [String]
		self.facebookId = None

		# Gender [String]
		self.genderEnum = None

		# Home phone [String]
		self.homePhone = None

		# IP address [String]
		self.ipAddress = None

		# Mobile Phone [String]
		self.mobilePhone = None

		# Work Phone [String]
		self.workPhone = None

		#  Buyer full name [String]
		self.name = None

		# Document number [String]
		self.taxDocumentNumber = None		

		# Twitter ID [String]
		self.twitterId = None		

		# List of addresses [List] 
		self.addressCollection = []

		# Buyer unique identification(GUID). Generated by Mundipagg
		self.buyerKey = '00000000-0000-0000-0000-000000000000'

		# *Person* for indivual people information or *Company* for enterprise information [String]
		self.personTypeEnum	= self.PersonTypeEnum.Person

		# CPF for person document number or CNPJ for company document number.
		self.taxDocumentTypeEnum = self.DocumentType.CPF