class ManageOrderRequest:

	#: Credit card transaction collection [List]
	transactionCollection = []		

	#: Operation enum [String]
	manageOrderOperationEnum = None

	#: Mundipagg merchant identification [GUID]
	merchantKey = None

	#: Unique order identification. Generated by MundiPagg [GUID]
	orderKey = None

	#: Order identifciation [String]
	orderReference	= None

	#: If not send, it will be generate automatically in the webservice and returned in response.
    #: Web service request identification, it is used for investigate problems with webservice requests.
    #: [Guid] 
	requestKey	= None
	
	operationEnum = None

	class OperationEnum:
		"""Operation Enum"""
		Capture = 'Capture'
		Void = 'Void'
			
	
	def __init__(self):
		self.requestKey	= '00000000-0000-0000-0000-000000000000'
		self.operationEnum = self.OperationEnum
		

	class ManageTransactionRequest:

		#: Order amount in cents [Long]
		amountInCents = None

		#: Unique transaction identifier generated by MundiPagg [GUID]
		transactionKey = None

		#: Custom transaction identifier [String]
		transactionReference = None

		def __init__(self):
			pass