class ManageOrderRequest:

	class OperationEnum:
		"""Operation Enum"""
		Capture = 'Capture'
		Void = 'Void'
			
	
	def __init__(self):
		# Credit card transaction collection [List]
		self.transactionCollection = []		

		# Operation enum [String]
		self.manageOrderOperationEnum = self.OperationEnum

		# Mundipagg merchant identification [GUID]
		self.merchantKey = None

		# Unique order identification. Generated by MundiPagg [GUID]
		self.orderKey = None

		# Order identifciation [String]
		self.orderReference	= None

		# If not send, it will be generate automatically in the webservice and returned in response.
        # Web service request identification, it is used for investigate problems with webservice requests.
        # [Guid] 
		self.requestKey	= '00000000-0000-0000-0000-000000000000'
		
		#self.operationEnum = self.OperationEnum

	class ManageTransactionRequest:

		def __init__(self):
			# Order amount in cents [Long]
			amountInCents = None

			# Unique transaction identifier generated by MundiPagg [GUID]
			transactionKey = None

			# Custom transaction identifier [String]
			transactionReference = None
													