class QueryOrderRequest:
	
	def __init__(self):
		# MundiPagg merchant identification [GUID]
		self.merchantKey = None

		# Unique order identification. Generated by MundiPagg
		self.orderKey = None

		# Custom order identification
		self.orderReference = None

		# If not send, it will be generate automatically in the webservice and returned in response.
        # Web service request identification, it is used for investigate problems with webservice requests.
        # [Guid]
		self.requestKey = '00000000-0000-0000-0000-000000000000'